import type { Metadata } from "../../$node_modules/next/index.js";
import "@repo/ui/globals.css";
import { AuthProvider } from "~/lib/auth/AuthProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<AuthProvider>
				<body>{children}</body>
			</AuthProvider>
		</html>
	);
}
